---
output: hugodown::md_document
title: About
type: "generic_page"
summary: "An R, sports analytics, and data viz website by Ryan Keeney"
---

# About the site

Welcome! The goal of this site is to make my code and projects accessible to other R enthusiasts, from beginners to potential employers. If enjoy my work, there's more of it on [Twitter](https://twitter.com/rbkeeney); and, if you have a question or comment my DMs are open.

If you'd like to support my work, [Patreon](https://www.patreon.com/rbkeeney) is currently the best place. Once you're a member, you'll get access to NFL Analytics and Fantasy football resources such as:

* Multiple Shiny Web Apps
* Rookie Projections and Models 
* Twitch Live-Streams
* Rookie and Player Ranks
* Playbooks for Redraft and Dynasty Leagues
* Curated Databases for Additional Analysis

# More R, Sports Analytics, and Data Viz Resources

Here are some of Ryan's favorite resources:

* [NFLfastR](https://mrcaseb.github.io/nflfastR/articles/beginners_guide.html)
* [TidyTuesday](https://thomasmock.netlify.app/post/tidytuesday-a-weekly-social-data-project-in-r/)
* [TidyModels](https://www.tidymodels.org/)
* [Yan Holtz's R Gallery](https://www.r-graph-gallery.com/)

# About the author

[Ryan Keeney](https://twitter.com/rbkeeney) is a aspiring data scientist with a passion for sports analytics, especially (American) football. After working 6 years as a mechanical engineer at John Deere and designing the Progator GPS PrecisionSprayer, he and his wife, Lydia, took a 1-year leave of absence to volunteer in Paraguay. While they were in Paraguay, Ryan's position was terminated due to the COVID-19 crisis so they decided to stay in South America. Currently, Ryan and Lydia are enjoying Paraguay and working remotely while Ryan applies to graduate school and learns things like ggplot, SQL, Python, statistics, modeling, and Git.

...y su español está mejorando. bueno, él piensa que sí.

If you'd like to contact Ryan, he's generally civil on [Twitter](https://twitter.com/rbkeeney) and does keep his DMs open. If you'd like to support Ryan,  [Patreon](https://www.patreon.com/rbkeeney) is still the best place.
